language: python
python:
  - "2.7"

# use it to install system wide python packages such as scipy
virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq python-numpy python-scipy python-glpk libglpk-dev glpk-utils

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pep8
  - pip list
  - python -c "import nltk; nltk.download('stopwords'); nltk.download('punkt')"

# test for pep8
before_script:
  - "pep8 potara/summarizer.py potara/document.py potara/similaritymeasures.py"

# command to run tests, e.g. python setup.py test
script:
  - "python setup.py test"
  - "coverage run --omit=potara/takahe.py --source=potara setup.py test"

after_success:
  coveralls